name: Publish 🚀

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
